version: '3.8'
services:
    php-apache-environment:
        container_name: php-apache
        build:
            context: ./php
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - ./:/var/www/html/
        ports:
            - 80:80
    db:
        container_name: db
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
            MYSQL_DATABASE: Password_Manager
            MYSQL_USER: User
            MYSQL_PASSWORD: Password
        ports:
            - "9906:3306"